[package]
name = "tod-web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = {version = "1", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0.121"
shuttle = "0.7.1"
shuttle-runtime = "0.46.0"
shuttle-axum = "0.46.0"
askama_axum = "0.4.0"
askama = "0.12.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.5.2", features = ["trace"] }

[dev-dependencies]
cargo-watch = "8.5.2"
axum-test = "15.3.0"
